### ISSUE TITLE
.github/marketplace.svg references dabian-stable instead of fedora-latest

### ISSUE THREAD

**Issue by Jakuje** [roles-ansible/check-ansible-fedora-latest-action#1]
The badge icon

https://github.com/roles-ansible/check-ansible-fedora-latest-action/blob/master/.github/marketplace.svg

lists debian instead of fedora. SVG file looks like rendered in the way that it needs modification in inkscape.

**Comment by DO1JLR** [comment]
uh, thanks. I forgot to update it.
